hw/ssi/axiqspi: Add missing default case
Add missing default case to fix:
/home/edgar/work/xilinx/m-arch/qemu/hw/ssi/xlnx-axiqspi.c: In function ‘axiqspi_xip_read’:
/home/edgar/work/xilinx/m-arch/qemu/hw/ssi/xlnx-axiqspi.c:1671:5: error: ‘cmd’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     ssi_transfer(s->spi_bus, cmd);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Edgar E. Iglesias <edgar.iglesias@xilinx.com>