COVER: Allow multiple CPU GDB debugging
---CHANGELOG---
PUBLIC

When debugging QEMU machines with differnet CPU types (like the Xilinx
ZynqMP machines with A53s and R5s) at the moment this is what connecting
a multi-arch GDB looks like:

>>> target extended-remote :1234
Remote debugging using :1234
0x0000000008000000 in ?? ()
Traceback (most recent call last):
  File "<string>", line 196, in <lambda>
  File "<string>", line 215, in on_stop
  File "<string>", line 252, in build
  File "<string>", line 1108, in lines
gdb.error: Could not fetch register "pc"; remote failure reply 'E14'
Could not fetch register "pc"; remote failure reply 'E14'
Could not fetch register "pc"; remote failure reply 'E14'

After this patch series (including the hack patch) this is the outcome:

>>> target extended-remote :1234
Remote debugging using :1234
warning: Architecture rejected target-supplied description
0x00000000 in ?? ()
>>> add-inferior
Added inferior 2
>>> inferior 2
[Switching to inferior 2 [<null>] (<noexec>)]
>>> attach 2
Attaching to process 2
warning: Architecture rejected target-supplied description
[New Thread 2.6]
[Switching to Thread 2.5]
0x00000000 in ?? ()
>>> info threads
  Id   Target Id         Frame
  6    Thread 2.6 (CPU#5 [halted ]) 0x00000000 in ?? ()
* 5    Thread 2.5 (CPU#4 [halted ]) 0x00000000 in ?? ()
  4    Thread 1.4 (CPU#3 [halted ]) 0x00000000 in ?? ()
  3    Thread 1.3 (CPU#2 [halted ]) 0x00000000 in ?? ()
  2    Thread 1.2 (CPU#1 [halted ]) 0x00000000 in ?? ()
  1    Thread 1.1 (CPU#0 [running]) 0x00000000 in ?? ()
---END---

Signed-off-by: Alistair Francis <alistair.francis@xilinx.com>